groups:
- name: develop
  jobs:
  - test-unit
  - test-integration
- name: release
  jobs:
  - release-major
  - release-minor
  - release-patch

jobs:
  - name: test-unit
    serial: true
    plan:
      - get: plugin
        trigger: true
      - get: ci
      - task: test-unit
        file: ci/ci/tasks/test-unit.yml

  - name: test-integration
    serial: true
    plan:
      - get: plugin
        passed: [test-unit]
        trigger: true
      - get: ci
      - task: test-integration
        file: ci/ci/tasks/test-integration.yml
        params:
          service_account_json: ((service_account_json))
          project_id:           ((project_id))

  - name: release-major
    serial: true
    plan:
      - get: plugin-release
      - get: ci
      - get: version
        params: {bump: major}
      - task: release
        file: ci/ci/tasks/release.yml
        input_mapping: {plugin: plugin-release}
        params:
          service_account_json: ((service_account_json))
          project_id:           ((project_id))
          artifactory_username: ((artifactory_username))
          artifactory_password: ((artifactory_password))
      - put: version
        params: {file: version/version}

  - name: release-minor
    serial: true
    plan:
      - get: plugin-release
      - get: ci
      - get: version
        params: {bump: minor}
      - task: release
        file: ci/ci/tasks/release.yml
        input_mapping: {plugin: plugin-release}
        params:
          service_account_json: ((service_account_json))
          project_id:           ((project_id))
          artifactory_username: ((artifactory_username))
          artifactory_password: ((artifactory_password))
      - put: version
        params: {file: version/version}

  - name: release-patch
    plan:
      - get: plugin-release
      - get: ci
      - get: version
        params: {bump: patch}
      - task: release
        file: ci/ci/tasks/release.yml
        input_mapping: {plugin: plugin-release}
        params:
          service_account_json: ((service_account_json))
          project_id:           ((project_id))
          artifactory_username: ((artifactory_username))
          artifactory_password: ((artifactory_password))
      - put: version
        params: {file: version/version}

resources:
- name: plugin
  type: git
  source:
    uri: ((repo_uri))
    branch: ((plugin_branch))

- name: plugin-release
  type: git
  source:
    uri: ((repo_uri))
    branch: ((release_branch))

- name: ci
  type: git
  source:
    uri: ((repo_uri))
    branch: ((ci_branch))
    paths:
        - ci/*

- name: version
  type: semver
  source:
    driver: git
    initial_version: 1.0.10
    uri: ((repo_uri))
    branch: ((release_branch))
    file: version
