jobs:
  - name: test-unit
    serial: true
    plan:
      - get: plugin
        trigger: true
      - get: ci
      - task: test-unit
        file: ci/ci/tasks/test-unit.yml

  - name: test-integration
    serial: true
    plan:
      - get: plugin
        passed: [test-unit]
        trigger: true
      - get: ci
      - task: test-integration
        file: ci/ci/tasks/test-integration.yml
        params:
          service_account_json: ((service_account_json))
          project_id:           ((project_id))

resources:
- name: plugin
  type: git
  source:
    uri: https://github.com/jenkinsci/google-compute-engine-plugin.git
    branch: ((plugin_branch))
- name: ci
  type: git
  source:
    uri: https://github.com/jenkinsci/google-compute-engine-plugin.git
    branch: ((ci_branch))
    paths:
        - ci/*
